
subjects:
  siemens:
    - '0066'
    - '0070'
    - '0076'
    - '0078'
    - '0079'
    - '0083'
    - '0084'
  ge:
    - P034
    - P035
    - P037
    - P041
    - P045
    - P046
    - P051
    - P054
    - P058

preproc_t1: '../epi_{prepost}_{site}/fmriprep_20.1.1/fmriprep/sub-{subject}/anat/sub-{subject}_desc-preproc_T1w.nii.gz'

#this now is set to be T1w space bold
preproc_bold:
  preop:
    siemens: '../epi_preop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_space-T1w_desc-preproc_bold.nii.gz'
    ge: '../epi_preop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_space-T1w_desc-preproc_bold.nii.gz'
  postop:
    siemens: '../epi_postop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_space-T1w_desc-preproc_bold.nii.gz'
    ge: '../epi_postop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_space-T1w_desc-preproc_bold.nii.gz'

preproc_bold_json:
  preop:
    siemens: '../epi_preop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_space-T1w_desc-preproc_bold.json'
    ge: '../epi_preop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_space-T1w_desc-preproc_bold.json'
  postop:
    siemens: '../epi_postop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_space-T1w_desc-preproc_bold.json'
    ge: '../epi_postop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_space-T1w_desc-preproc_bold.json'


preproc_mask:
  preop:
    siemens: '../epi_preop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_space-T1w_desc-brain_mask.nii.gz'
    ge: '../epi_preop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_space-T1w_desc-brain_mask.nii.gz'
  postop:
    siemens: '../epi_postop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_space-T1w_desc-brain_mask.nii.gz'
    ge: '../epi_postop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_space-T1w_desc-brain_mask.nii.gz'




preproc_confounds:
  preop:
    siemens: '../epi_preop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_desc-confounds_regressors.tsv'
    ge: '../epi_preop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_desc-confounds_regressors.tsv'
  postop:
    siemens: '../epi_postop_siemens/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_desc-confounds_regressors.tsv'
    ge: '../epi_postop_ge/fmriprep_20.1.1/fmriprep/sub-{subject}/func/sub-{subject}_task-{task}_run-1_desc-confounds_regressors.tsv'



warp_pre_to_mni: '../epi_preop_{site}/fmriprep_20.1.1/fmriprep/sub-{subject}/anat/sub-{subject}_from-T1w_to-{space}_mode-image_xfm.h5'
warp_mni_to_pre: '../epi_preop_{site}/fmriprep_20.1.1/fmriprep/sub-{subject}/anat/sub-{subject}_from-{space}_to-T1w_mode-image_xfm.h5'
rigid_post_to_pre: '../epi_preop_{site}/resection_masks/sub-{subject}/sub-{subject}_from-postop_to-preop_desc-rigid_xfm.txt'
warp_post_to_pre: '../epi_preop_{site}/resection_masks/sub-{subject}/warp.nii.gz'
warp_pre_to_post: '../epi_preop_{site}/resection_masks/sub-{subject}/inverse_warp.nii.gz'



denoise:
  24HMP8PhysSpikeReg:
    clean_img_opts:
      standardize: True
      detrend: False
      low_pass: 0.08
      high_pass: 0.01
    confounds_name:
      - csf 
      - csf_derivative1 
      - csf_derivative1_power2
      - csf_power2 
    confounds_like:
      - white_matter
      - trans
      - rot
      - motion_outlier
      - steady_state_outlier


ants_container: /project/6050199/akhanf/singularity/bids-apps/khanlab_neuroglia-core_latest.sif

